name: OceanPractice
version: 1.0
main: lol.oce.marine.Practice
depend:
  - TitleAPI
commands:
  arena:
  kit:
  duel:
    aliases: [d]
  practice:
    aliases: ["practice", "oprac", "oceanpractice"]
  drop:
  duplicate:
  test: